### ISSUE TITLE
Empty string where there should be no entry for previous link in 1st Congress

### ISSUE THREAD

**Issue by lmullen** [mapping-elections/mappingelections#12]
There is a minor bug in creating the array for related maps. For the first Congress, the previous link should be non-existent, but instead it is an empty string. For example:

```
related-maps:
- ''
- id: meae.congressional.congress02.ny.county
  name: NY Second Congress
  type: next
- id: meae.congressional.congress01.national.district
  name: National First Congress
  type: national
```

@jfbratt Could you please work on this and submit a pull request in a new branch?
